# Generated by Django 6.0.6 on 2026-06-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('review_count', models.IntegerField(null=True)),
                ('revenue_1year', models.FloatField(null=True)),
                ('screenshot_urls', models.JSONField(default=list, null=True)),
                ('capsule_url', models.URLField(max_length=500, null=True)),
                ('review_count_1year', models.FloatField(null=True)),
                ('review_impression', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='games.game')),
            ],
        ),
    ]
