# Generated by Django 6.0.6 on 2026-06-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamepad_support',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='languages',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='multiplayer_support',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steamdeck_support',
            field=models.JSONField(default=list, null=True),
        ),
    ]
