# Generated by Django 6.0.6 on 2026-06-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_gamepad_support_game_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='features',
            field=models.JSONField(default=list, null=True),
        ),
    ]
