# Generated by Django 5.2.9 on 2026-07-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_feature_gamepadsupport_language_multiplayersupport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_br',
            field=models.BooleanField(default=False),
        ),
    ]
