# Generated by Django 6.0.6 on 2026-07-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_features'),
        ('games', '0003_game_is_br'),
    ]

    operations = [
    ]
